# Domaine: SCIENCES ET TECHNOLOGIE
# Mention: PHYSIQUE
# Spécialité: PHOTONIQUE
# Grade: MASTER
# Niveau: M1
# Semestre: 1

[semestre_1.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
mention = "PHYSIQUE"
specialite = "PHOTONIQUE"
grade = "MASTER"
niveau = "M1"
semestre = 1

[[semestre_1.ue_connaissances_fondamentales]]
code_ue = "PHS2221"
intitule_ue = "Physique du Solide"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr KRE N'guessan, MC"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "PHS22211"
  intitule_ecue = "Structures cristallines"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "PHS22212"
  intitule_ecue = "Propriétés électroniques"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_connaissances_fondamentales]]
code_ue = "IRM2221"
intitule_ue = "Interactions Rayonnements-Matière"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr KRE N'guessan, MC"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "IRM22211"
  intitule_ecue = "Rayonnements"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "IRM22212"
  intitule_ecue = "Interactions"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_connaissances_fondamentales]]
code_ue = "SIG2221"
intitule_ue = "Signaux"
credit = 4
cect_ue = 4
enseignant_responsable = "Dr OUATTARA Sié, MC"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "SIG22211"
  intitule_ecue = "Traitement de Signaux"
  cm = 12
  td = 12
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_1.ue_connaissances_fondamentales.ecue]]
  code_ecue = "SIG22212"
  intitule_ecue = "Analyse de Signaux"
  cm = 0
  td = 0
  tp = 24
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_specialite]]
code_ue = "TMI2221"
intitule_ue = "Technique en Microscopie"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_1.ue_specialite.ecue]]
  code_ecue = "TMI22211"
  intitule_ecue = "Microscopie de fluorescence"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_1.ue_specialite.ecue]]
  code_ecue = "TMI22212"
  intitule_ecue = "Microscopie à contraste de phase"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_methodologie]]
code_ue = "ASM2221"
intitule_ue = "Analyse Statistique Multivariée"
credit = 4
cect_ue = 4
enseignant_responsable = "Pr ASSIDJO Emmanuel"

  [[semestre_1.ue_methodologie.ecue]]
  code_ecue = "ASM22211"
  intitule_ecue = "Planification expérimentale"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_1.ue_methodologie.ecue]]
  code_ecue = "ASM22212"
  intitule_ecue = "Analyse Multivariable de données"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_methodologie]]
code_ue = "MNL2221"
intitule_ue = "Méthode Numérique et Logiciels Scientifiques"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr ZEZE Sylvain, MA"

  [[semestre_1.ue_methodologie.ecue]]
  code_ecue = "MNL2221"
  intitule_ecue = "Méthode Numérique et Logiciels Scientifiques"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_1.ue_culture_generale]]
code_ue = "UEL2221"
intitule_ue = "UE Libre"
credit = 1
cect_ue = 1
enseignant_responsable = "Dr TOURE Jules, MA"

  [[semestre_1.ue_culture_generale.ecue]]
  code_ecue = "UEL2221"
  intitule_ecue = "UE Libre"
  cm = 12
  td = 0
  tp = 0
  projet = 0
  total_he = 12
  tpe = 13
  ctt = 25
  credit_ecue = 1
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[semestre_1.total]
cm = 324
td = 12
tp = 24
projet = 0
total_he = 360
tpe = 390
ctt = 750
credit_total = 30

# Domaine: SCIENCES ET TECHNOLOGIE
# Mention: PHYSIQUE
# Spécialité: PHOTONIQUE
# Grade: MASTER
# Niveau: M1
# Semestre: 2

[semestre_2.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
mention = "PHYSIQUE"
specialite = "PHOTONIQUE"
grade = "MASTER"
niveau = "M1"
semestre = 2

[[semestre_2.ue_connaissances_fondamentales]]
code_ue = "CRT2222"
intitule_ue = "Cristallographie"
credit = 5
cect_ue = 5
enseignant_responsable = "Pr YAO Rita"

  [[semestre_2.ue_connaissances_fondamentales.ecue]]
  code_ecue = "CRT22221"
  intitule_ecue = "Structures"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_2.ue_connaissances_fondamentales.ecue]]
  code_ecue = "CRT22222"
  intitule_ecue = "Applications"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_connaissances_fondamentales]]
code_ue = "SPE2222"
intitule_ue = "Spectroscopie"
credit = 5
cect_ue = 5
enseignant_responsable = "Pr YAO Rita"

  [[semestre_2.ue_connaissances_fondamentales.ecue]]
  code_ecue = "SPE22221"
  intitule_ecue = "Spectroscopie d'absorption et d'émission atomique"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_2.ue_connaissances_fondamentales.ecue]]
  code_ecue = "SPE22222"
  intitule_ecue = "Spectroscopie de fluorescence (UV). Spectrométrie de masse"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_specialite]]
code_ue = "NAN2222"
intitule_ue = "Nanostructures et Nanophysique"
credit = 4
cect_ue = 4
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_2.ue_specialite.ecue]]
  code_ecue = "NAN22221"
  intitule_ecue = "Nanostructure"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_2.ue_specialite.ecue]]
  code_ecue = "NAN22222"
  intitule_ecue = "Nanophysique"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_specialite]]
code_ue = "OQO2222"
intitule_ue = "Optique Quantique et Optoélectronique"
credit = 4
cect_ue = 4
enseignant_responsable = "Dr KRE N'guessan, MC"

  [[semestre_2.ue_specialite.ecue]]
  code_ecue = "OQO22221"
  intitule_ecue = "Optique quantique"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_2.ue_specialite.ecue]]
  code_ecue = "OQO22222"
  intitule_ecue = "Optoélectronique"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_specialite]]
code_ue = "IMA2222"
intitule_ue = "Imagerie"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr LOUME Georges, MC"

  [[semestre_2.ue_specialite.ecue]]
  code_ecue = "IMA2222"
  intitule_ecue = "Imagerie"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_methodologie]]
code_ue = "IOF2222"
intitule_ue = "Introduction à l'Optique de Fourier"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_2.ue_methodologie.ecue]]
  code_ecue = "IOF2222"
  intitule_ecue = "Introduction à l'Optique de Fourier"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_culture_generale]]
code_ue = "RDS2222"
intitule_ue = "Réduction Scientifique"
credit = 2
cect_ue = 2
enseignant_responsable = "Pr OUATTARA Alassane"

  [[semestre_2.ue_culture_generale.ecue]]
  code_ecue = "RDS2222"
  intitule_ecue = "Réduction Scientifique"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_culture_generale]]
code_ue = "ENT2222"
intitule_ue = "Entrepreneuriat"
credit = 1
cect_ue = 1
enseignant_responsable = "M. KABA Mohamed Lamine"

  [[semestre_2.ue_culture_generale.ecue]]
  code_ecue = "ENT2222"
  intitule_ecue = "Entrepreneuriat"
  cm = 12
  td = 0
  tp = 0
  projet = 0
  total_he = 12
  tpe = 13
  ctt = 25
  credit_ecue = 1
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_2.ue_culture_generale]]
code_ue = "ANS2222"
intitule_ue = "Anglais"
credit = 3
cect_ue = 3
enseignant_responsable = "M. GBEADA Marius"

  [[semestre_2.ue_culture_generale.ecue]]
  code_ecue = "ANS2222"
  intitule_ecue = "Anglais"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[semestre_2.total]
cm = 360
td = 0
tp = 0
projet = 0
total_he = 360
tpe = 390
ctt = 750
credit_total = 30