# Domaine: SCIENCES ET TECHNOLOGIE
# Parcours: PHYSIQUE-CHIMIE
# Grade: LICENCE
# Niveau: L2
# Semestre: 3

[semestre_3.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
parcours = "PHYSIQUE-CHIMIE"
grade = "LICENCE"
niveau = "L2"
semestre = 3

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "MAN2103"
intitule_ue = "Integrations et Series"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "MAN21031"
intitule_ecue = "Integrales generalisees et Series de fonctions"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "MAN21032"
intitule_ecue = "Series entieres-Series de Fourier"

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "CHO2103"
intitule_ue = "Chimie Organique 1"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "CHO21031"
intitule_ecue = "Hydrocarbures"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "CHO21032"
intitule_ecue = "Composes organiques fonctici"

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "CHM2103"
intitule_ue = "Chimie Minerale"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "CHM21031"
intitule_ecue = "Classification des elements chimiques"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "CHM21032"
intitule_ecue = "Proprietes des elements chimiques"

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "PBS2103"
intitule_ue = "Probabilite- Statistique"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "PBS21031"
intitule_ecue = "Probabilites"

[[semestre_3.ue_connaissances_fondamentales.ecue]]
code_ecue = "PBS21032"
intitule_ecue = "Statistique"

[[semestre_3.ue_methodologie]]
code_ue = "INP2103"
intitule_ue = "Introduction à la programmation"

[[semestre_3.ue_methodologie.ecue]]
code_ecue = "INP2103"
intitule_ecue = "Introduction à la programmation"

[[semestre_3.ue_methodologie]]
code_ue = "MSP2103"
intitule_ue = "Mathematiques pour les Sciences-Physiques"

[[semestre_3.ue_methodologie.ecue]]
code_ecue = "MSP2103"
intitule_ecue = "Mathematiques pour les Sciences-Physiques"

[[semestre_3.ue_culture_generale]]
code_ue = "ANG2103"
intitule_ue = "Anglais"

[[semestre_3.ue_culture_generale.ecue]]
code_ecue = "ANG2103"
intitule_ecue = "Anglais"

# Domaine: SCIENCES ET TECHNOLOGIE
# Parcours: PHYSIQUE-CHIMIE
# Grade: LICENCE
# Niveau: L2
# Semestre: 4

[semestre_4.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
parcours = "PHYSIQUE-CHIMIE"
grade = "LICENCE"
niveau = "L2"
semestre = 4

[[semestre_4.ue_connaissances_fondamentales]]
code_ue = "MEM2104"
intitule_ue = "Mecanique des Systemes"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "MEM21041"
intitule_ecue = "Elements de base de la mecanique des systemes"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "MEM21042"
intitule_ecue = "Applications aux systemes materiels"

[[semestre_4.ue_connaissances_fondamentales]]
code_ue = "ELE2104"
intitule_ue = "Electromagnetisme"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "ELE2104"
intitule_ecue = "Electromagnetisme"

[[semestre_4.ue_connaissances_fondamentales]]
code_ue = "OPO2104"
intitule_ue = "Optique Ondulatoire"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "OPO2104"
intitule_ecue = "Optique Ondulatoire"

[[semestre_4.ue_connaissances_fondamentales]]
code_ue = "PMQ2104"
intitule_ue = "Mecanique Quantique"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "PMQ21041"
intitule_ecue = "Notions de base"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "PMQ21042"
intitule_ecue = "Applications"

[[semestre_4.ue_connaissances_fondamentales]]
code_ue = "PTH2104"
intitule_ue = "Thermodynamique Physique"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "PTH21041"
intitule_ecue = "Principes de la thermodynamie"

[[semestre_4.ue_connaissances_fondamentales.ecue]]
code_ecue = "PTH21042"
intitule_ecue = "Applications"

[[semestre_4.ue_methodologie]]
code_ue = "PHP2104"
intitule_ue = "Physique Pratique"

[[semestre_4.ue_methodologie.ecue]]
code_ecue = "PHP2104"
intitule_ecue = "Physique Pratique"

[[semestre_4.ue_methodologie]]
code_ue = "CHP2104"
intitule_ue = "Chimie Pratique"

[[semestre_4.ue_methodologie.ecue]]
code_ecue = "CHP21041"
intitule_ecue = "Chimie Generale"

[[semestre_4.ue_methodologie.ecue]]
code_ecue = "CHP21042"
intitule_ecue = "Chimie Organique"

[[semestre_4.ue_culture_generale]]
code_ue = "UEL2104"
intitule_ue = "UE Libre"

[[semestre_4.ue_culture_generale.ecue]]
code_ecue = "UEL2104"
intitule_ecue = "UE Libre"
