# Domaine: SCIENCES ET TECHNOLOGIE
# Parcours/ Mention: MATHEMATIQUES
# Spécialité: ALGEBRE COMMUTATIVE ET CRYPTOGRAPHIE (ACC)
# Grade: MASTER
# Niveau: M2
# Semestre: 3

[semestre_3.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
parcours_mention = "MATHEMATIQUES"
specialite = "ALGEBRE COMMUTATIVE ET CRYPTOGRAPHIE (ACC)"
grade = "MASTER"
niveau = "M2"
semestre = 3

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "AFA2313"
intitule_ue = "Analyse Fonctionnelle Approfondie"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr FEUTO, MC"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "AFA23131"
  intitule_ecue = "Théorèmes Fondamentaux de l'Analyse fonctionnelle"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "AFA23132"
  intitule_ecue = "Mesures Complexes et de Radon - Transformation de Fourier"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "PRA2313"
intitule_ue = "Probabilités Avancées"
credit = 6
cect_ue = 6
enseignant_responsable = "Pr N'ZI Modeste"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "PRA23131"
  intitule_ecue = "Eléments de théorie des Martingales"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "PRA23132"
  intitule_ecue = "Algorithms stochastiques de résolution de problèmes"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "TEF2313"
intitule_ue = "Théories des filtrations"
credit = 6
cect_ue = 6
enseignant_responsable = "Pr SANGARE Daouda"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "TEF23131"
  intitule_ecue = "Filtration des anneaux gradués associés"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "TEF23132"
  intitule_ecue = "Quasi-polynômes de Hilbert"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "CRY2313"
intitule_ue = "Cryptographie"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr DIAGANA Youssouf, MC"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "CRY23131"
  intitule_ecue = "Cryptologie classiques et compléments mathématiques"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "CRY23132"
  intitule_ecue = "Cryptographie publique et cryptanalyse"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_methodologie]]
code_ue = "PRL2313"
intitule_ue = "Programmation linéaire"
credit = 2
cect_ue = 2
enseignant_responsable = "Dr EDI Kouassi Hilaire, MA"

  [[semestre_3.ue_methodologie.ecue]]
  code_ecue = "PRL2313"
  intitule_ecue = "Programmation linéaire"
  cm = 24
  td = 0
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_culture_generale]]
code_ue = "TEX2313"
intitule_ue = "Techniques d'expression française"
credit = 2
cect_ue = 2
enseignant_responsable = "Dr DIAGANA Youssouf, MC"

  [[semestre_3.ue_culture_generale.ecue]]
  code_ecue = "TEX2313"
  intitule_ecue = "Techniques d'expression française"
  cm = 12
  td = 12
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_culture_generale]]
code_ue = "ANG2313"
intitule_ue = "Anglais"
credit = 2
cect_ue = 2
enseignant_responsable = "M. GBEADA Marius"

  [[semestre_3.ue_culture_generale.ecue]]
  code_ecue = "ANG2313"
  intitule_ecue = "Anglais"
  cm = 12
  td = 12
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[semestre_3.total]
cm = 288
td = 24
tp = 0
projet = 0
total_he = 312
tpe = 338
ctt = 650
credit_total = 30


# Domaine: SCIENCES ET TECHNOLOGIE
# Parcours/ Mention: MATHEMATIQUES
# Spécialité: ALGEBRE COMMUTATIVE ET CRYPTOGRAPHIE (ACC)
# Grade: MASTER
# Niveau: M2
# Semestre: 4

[semestre_4.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
parcours_mention = "MATHEMATIQUES"
specialite = "ALGEBRE COMMUTATIVE ET CRYPTOGRAPHIE (ACC)"
grade = "MASTER"
niveau = "M2"
semestre = 4

[[semestre_4.ue_methodologie]]
code_ue = "RDS2314"
intitule_ue = "Réduction Scientifique"
credit = 2
cect_ue = 2
enseignant_responsable = "Pr TANOH Hilaire"

  [[semestre_4.ue_methodologie.ecue]]
  code_ecue = "RDS2314"
  intitule_ecue = "Réduction Scientifique"
  cm = 12
  td = 12
  tp = 0
  projet = 0
  total_he = 24
  tpe = 26
  ctt = 50
  credit_ecue = 2
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_4.ue_methodologie]]
code_ue = "STM2314"
intitule_ue = "Stage et Mémoire"
credit = 28
cect_ue = 28
enseignant_responsable = "Pr SANGARE Daouda"

  [[semestre_4.ue_methodologie.ecue]]
  code_ecue = "STM2314"
  intitule_ecue = "Stage et Mémoire"
  cm = 0
  td = 0
  tp = 0
  projet = 336
  total_he = 336
  tpe = 364
  ctt = 700
  credit_ecue = 28

[semestre_4.total]
cm = 12
td = 12
tp = 0
projet = 336
total_he = 360
tpe = 390
ctt = 750
credit_total = 30