# Domaine: SCIENCES ET TECHNOLOGIE
# Mention: PHYSIQUE
# Spécialité: PHOTONIQUE
# Grade: MASTER
# Niveau: M2
# Semestre: 3

[semestre_3.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
mention = "PHYSIQUE"
specialite = "PHOTONIQUE"
grade = "MASTER"
niveau = "M2"
semestre = 3

[[semestre_3.ue_connaissances_fondamentales]]
code_ue = "CIE2223"
intitule_ue = "Circuits et Instrumentations Electroniques"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr OUATTARA Sié, MC"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "CIE22231"
  intitule_ecue = "Circuits Electroniques"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_connaissances_fondamentales.ecue]]
  code_ecue = "CIE22232"
  intitule_ecue = "Instrumentations Electronique"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "OPA2223"
intitule_ue = "Optique Avancée"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "OPA22231"
  intitule_ecue = "Optique Nonlinéaire"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "OPA22232"
  intitule_ecue = "Optique Guidée"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "LAS2223"
intitule_ue = "Lasers"
credit = 6
cect_ue = 6
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "LAS22231"
  intitule_ecue = "Description des Laser"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "LAS22232"
  intitule_ecue = "Principaux Lasers : technologie et applications"
  cm = 36
  td = 0
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "OMO2223"
intitule_ue = "Outils de Modélisation"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr KRE N'guessan, MC"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "OMO2223"
  intitule_ecue = "Outils de Modélisation"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_specialite]]
code_ue = "SPE2223"
intitule_ue = "Spectroscopie Avancée"
credit = 3
cect_ue = 3
enseignant_responsable = "Pr ZOUEU Jérémie"

  [[semestre_3.ue_specialite.ecue]]
  code_ecue = "SPE2223"
  intitule_ecue = "Spectroscopie Avancée"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "IPP2223"
intitule_ue = "Initiation à la Physique du Plasma"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr KOUAKOU Ahoutou, MA"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "IPP2223"
  intitule_ecue = "Initiation à la Physique du Plasma"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "IPF2223"
intitule_ue = "Initiation à la physique de couches minces"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr KOUAKOU Ahoutou, MA"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "IPF2223"
  intitule_ecue = "Initiation à la physique de couches minces"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "ITR2223"
intitule_ue = "Initiation à la Théorie de la Relativité"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr MOUSSE Logbo, MC"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "ITR2223"
  intitule_ecue = "Initiation à la Théorie de la Relativité"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "TCA2223"
intitule_ue = "Techniques de caractérisation de matériaux"
credit = 3
cect_ue = 3
enseignant_responsable = "Dr KRE N'guessan, MC"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "TCA2223"
  intitule_ecue = "Techniques de caractérisation de matériaux"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "EEO2223"
intitule_ue = "Effets Electro-optiques"
credit = 3
cect_ue = 3
enseignant_responsable = "Pr MEGNASSAN Edjem"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "EEO2223"
  intitule_ecue = "Effets Electro-optiques"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[[semestre_3.ue_optionnelles]]
code_ue = "MMM2223"
intitule_ue = "Modélisation Moléculaire : Matière molle"
credit = 3
cect_ue = 3
enseignant_responsable = "Pr MEGNASSAN Edjem"

  [[semestre_3.ue_optionnelles.ecue]]
  code_ecue = "MMM2223"
  intitule_ecue = "Modélisation Moléculaire : Matière molle"
  cm = 18
  td = 18
  tp = 0
  projet = 0
  total_he = 36
  tpe = 39
  ctt = 75
  credit_ecue = 3
  evaluation_cc = "40 %"
  evaluation_et = "60 %"

[semestre_3.total]
cm = 288
td = 72
tp = 0
projet = 0
total_he = 360
tpe = 390
ctt = 750
credit_total = 30

# Domaine: SCIENCES ET TECHNOLOGIE
# Mention: PHYSIQUE
# Spécialité: PHOTONIQUE
# Grade: MASTER
# Niveau: M2
# Semestre: 4

[semestre_4.metadata]
domaine = "SCIENCES ET TECHNOLOGIE"
mention = "PHYSIQUE"
specialite = "PHOTONIQUE"
grade = "MASTER"
niveau = "M2"
semestre = 4

[[semestre_4.ue_methodologie]]
code_ue = "STM2224"
intitule_ue = "Stage et Mémoire"
credit = 30
cect_ue = 30
enseignant_responsable = "Dr BOSSON Jocelyne, MC"

  [[semestre_4.ue_methodologie.ecue]]
  code_ecue = "STM2224"
  intitule_ecue = "Stage et Mémoire"
  cm = 0
  td = 0
  tp = 0
  projet = 360
  total_he = 360
  tpe = 390
  ctt = 750
  credit_ecue = 30
  evaluation_cc = ""
  evaluation_et = ""

[semestre_4.total]
cm = 0
td = 0
tp = 0
projet = 360
total_he = 360
tpe = 390
ctt = 750
credit_total = 30
